spring:
  datasource:
    name: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    open-in-view:
    generate-ddl: true
    hibernate:
      ddl-auto: update

jwt:
  algorithm:
    key: secret
  token:
    token-lifetime: 15
    email-token-lifetime: 5
mail:
  from: "test"
app:
  frontend:
    url: "[::1]:8080/api/v1/auth/verify"

# SMTP configuration
gmail:
  host: localhost
  port: 25
#spring.mail.username=
#spring.mail.password=
#spring.properties.mail.smtp.auth=true
#spring.properties.mail.smtp.starttls.enable=true